[2024-03-19T21:24:19.759+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_with_python_operator_v1.get- manual__2024-03-19T21:24:18.447167+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
