[2024-03-20T04:26:45.737+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_cron_expression_v2.first_task scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-20T04:26:45.740+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_cron_expression_v2.first_task scheduled__2024-03-19T00:00:00+00:00 [queued]>
[2024-03-20T04:26:45.740+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 6
[2024-03-20T04:26:45.745+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): first_task> on 2024-03-19 00:00:00+00:00
[2024-03-20T04:26:45.748+0000] {standard_task_runner.py:60} INFO - Started process 11084 to run task
[2024-03-20T04:26:45.750+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_cron_expression_v2', 'first_task', 'scheduled__2024-03-19T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_cron_expression.py', '--cfg-path', '/tmp/tmpwg3e6p9s']
[2024-03-20T04:26:45.751+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask first_task
[2024-03-20T04:26:45.780+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_cron_expression_v2.first_task scheduled__2024-03-19T00:00:00+00:00 [running]> on host be400aaaf05d
[2024-03-20T04:26:45.810+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hitesh' AIRFLOW_CTX_DAG_ID='dag_with_cron_expression_v2' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T00:00:00+00:00'
[2024-03-20T04:26:45.811+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-20T04:26:45.811+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello world!']
[2024-03-20T04:26:45.815+0000] {subprocess.py:86} INFO - Output:
[2024-03-20T04:26:45.816+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: Hello: command not found
[2024-03-20T04:26:45.816+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-03-20T04:26:45.821+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-03-20T04:26:45.822+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_cron_expression_v2, task_id=first_task, execution_date=20240319T000000, start_date=20240320T042645, end_date=20240320T042645
[2024-03-20T04:26:45.827+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 11084)
[2024-03-20T04:26:45.848+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-20T04:26:45.856+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
